title: Jekyll 8bit
description: A Jekyll theme inspired by classic 8bit games.
theme: jekyll-theme-8bit
logo: nes-kirby
show_downloads: true
permalink: /:year/:month/:title.html
pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
social:
  twitter: https://twitter.com/username
  facebook: https://facebook.com/username
  github: https://github.com/username
  youtube: https://youtube.com/channel/ID
  google: https://plus.google.com/username
  medium: https://medium.com/@username
  twitch: https://twitch.com/username
  reddit: https://www.reddit.com/user/username
  whatsapp: tel:+5541999999999
  gmail: mailto:username@domain.net
  linkedin: https://www.linkedin.com/in/username
